# Generated by Django 4.2.7 on 2024-01-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_patient_assigneddoctorid_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.TextField(choices=[('finished', 'Finished'), ('available', 'Available'), ('occupied', 'Occupied')], default='available'),
        ),
    ]
